api/Device.go

Hi,
Ran into the problem when code like this panics because the `chars` map is not initialized:
```
api.On("discovery", emitter.NewCallback(func(ev emitter.Event) {
e := ev.GetData().(api.DiscoveredDeviceEvent)
e.GetCharByUUID(uuid) // here
}))
```
```
github.com/muka/go-bluetooth/api.(*Device).GetCharByUUID(0x10d916e0, 0x10e1e1e0, 0x24, 0x0, 0x1, 0x1)
github.com/muka/go-bluetooth/api/Device.go:257 +0x358
...
```
This PR fixes it.

Fix nil map panic

---

bluez/profile/GattCharacteristic1.go

I noticed that when adding a notify to a characteristic, the way of filtering out the non-important messages could be simplified. One way is to add the path as part of the characteristic struct itself. There could be something I'm overlooking here. Let me know!

Determining the path/source of an update makes sorting of notifications easier

---

api/Device.go

Related to #28 
This solves the issue of any nil `profile.GattCharacteristic1`from being created and then referenced later on. This does break caching of characteristics though until we can 100% be certain during any stage of a system and connection that we will get all the characteristics when `GetCharsList()` is called the first time.

Nil pointer dereference

---

api/Device.go
api/Manager.go
bluez/Client.go
bluez/profile/Device1.go
bluez/profile/GattCharacteristic1.go
bluez/profile/GattDescriptor1.go
bluez/profile/GattService1.go
bluez/profile/ObjectManager.go

I have found a bug in the library affecting the Device.watchProperties go-routine: its signaling channel never gets closed. A proper deregistration from the dbus library was missing as well. As this problem will most probaby be the same for oher structs, I have added a channel parameter to every Unregister function of every struct whose Register function spits out a channel.

unregister and close dbus channels properly

---

service/GattCharacteristic1.go
service/GattDescriptor1.go
service/GattService1.go

The introspection expects any exported methods to have a dbus.Error pointer as the final output, but the ReadValue/WriteValue and similar methods do not presently have this format.  Changing the method signatures causes them to work properly.
This fixes #30 in the repository issues list.
(Unfortunately, the service package still needs a fair amount of work; right now, the subscription and notification functionality doesn't really work properly, nor is there any easy way to actually provide or get values from a GattCharacteristic1.  But at least this corrects that one issue.)

Fix for DBus introspection of methods

---

bluez/profile/GattCharacteristic1.go
bluez/profile/GattDescriptor1.go
service/Application.go
service/GattCharacteristic1.go
service/GattDescriptor1.go

Add Read/Write callbacks (to allow dynamic data), and UpdateValue which can actually handle notifications properly.
By default, if no callbacks are added to the application, characteristics and descriptors will just store the value written to them (if writable), return the current value (if readable), and allow the value to be updated via UpdateValue() calls (which will notify any subscribers).  If callbacks are added, all behavior is up to the callback (writing to a characteristic does not necessarily update a value).
This is not _extensively_ tested, but seems to work better than the previous cut.  Might want to decide whether the callbacks are the best method of doing completely dynamic behavior on Write/Read.

First cut of fully working service functionality

---

Gopkg.lock
Gopkg.toml
api/Manager.go
bluez/profile/GattManager1.go
bluez/profile/obex/ObexClient1.go
devices/sensortag.go
examples/btmgmt/main.go
examples/discovery/main.go
examples/hci_updown/main.go
examples/obex_push/main.go
examples/sensortag_info/main.go
examples/sensortag_temperature/main.go
examples/service/client.go
examples/service/main.go
examples/service/service.go
examples/show_info/main.go
examples/watch_changes/main.go
linux/cmdexec.go
linux/rfkill.go
service/GattCharacteristic1.go
service/ObjectManager.go
service/Properties.go

The upstream repository URL of logrus has changed a few months ago. Quoting logrus's README:
```
The organization's name was changed to lower-case--and this will not be changed back. If you are getting import conflicts due to case sensitivity, please use the lower-case import: github.com/sirupsen/logrus.
```
Sadly this naming collision makes it impossible to use go-bluetooth alongside any other dependency that already imports the canonical URL with the lowercase 'sirupsen'.

Fixed upstream URL of logrus

---

api/Device.go

If device object expose a Device.On method which internally calls Device.watchProperties, it is natural that we expected changes related only to this device, not to all other devices. This change adds filtering by Signal.Path in watcher go routine.

filter not related to device PropertiesChangedchange events

---

api/Device.go
examples/discovery/main.go

I found that calling api.ClearDevices caused an issue with subsequent device calls (especially api.GetDevices()) as api.GetDeviceList's call to Manager.GetObjects|() would return objects that had been cleared from the cache) would fail.
Calling Flush calls adapter.RemoveDevice(...) as well as clearing it.
I have updated the discovery example to show its use, and prove that it works.

Added FlushDevices to remove and clear cached devices

---

api/Device.go
api/api.go
bluez/Client.go
bluez/profile/AgentManager1.go

api/Device.go
Pair() needs to  do a  return job to indicate the status of pairing ,like failed ,etc
bluez/Client.go
dbus.MakeVariant() is required to make the interface v to be an acceptable data format for dbus 
bluez/profile/AgentManager1.go
changed a lot, I wrote a test program called simple_agent.go this afternoon use this AgentManager1.go
well tested ,no problem with duplicate paring, and paring also return the result
but there will be a issue: no where to control the paring timeout 
my test program is here:
https://gist.github.com/cuu/a43f0c0c666e4ea61e3dece310803318
just change the **dev_mac** of your device  in main() 
I use logitech bluetooth keyboard K480 for testing 
works well
Sorry if there are  any questions, including code style, please modify them freely
I don't understand …

bug fix and test AgentManager1

---

devices/sensortag_humidity.go

The Read method previously used `calcTmpLocal` to convert the read from the sensortag, which is obviously wrong.

sensortag: fix wrong humidity calculation

---

service/Application.go
service/GattCharacteristic1.go

It would be great if it was possible to combine characteristics and descriptors with fixed `Value`s and those that are read and wrote to through the read and write handlers.
For that, I had to make a slight change in my fork of this project, so that when a handler returns a `service.NewCallbackError(service.CallbackNotRegistered, "")`, the `*CallbackError` gets passed through, so that the `Value` is used.
```
// my example read handler
func (a *gattApp) handleRead(app *service.Application, serviceUuid string, characteristicUuid string) ([]byte, error) {
if readHandler, ok := a.readHandlers[characteristicUuid]; ok {
return readHandler()
}
return nil, service.NewCallbackError(service.CallbackNotRegistered, "No callback registered.")
}
```

Pass through *CallbackError created in read and write handlers

---

bluez/profile/GattCharacteristic1.go

remove private channel in GattCharacteristic1, simplify Register()/Unregister():
- registering again after unregistering doesn't work - d.channel is not nil after Unregister(), but it's closed
- comparing to profile.Device's Register/Unregister this is unnecessarily different
remove it altogether, let user close the channel after unregistering.

simplify profile.GattCharacteristic1 Register/Unregister

---

service/Application.go
service/GattCharacteristic1.go
service/GattDescriptor1.go

- While using automation IO service, we can have multiple digital and analog characteristics. Each digital and analog characteristic has UUID 0x2A56 and 0x2A58 respectively.
- Problem : it was not possible to identify that which analog or digital characteristic has been changed. This is because, we have application callbacks where we use characteristic UUID
to identify the characteristic that has been changed.
- To fix this problem, dbus.ObjectPath are used instead of UUIDs of service, characteristic and descriptor. DBus object paths are guaranteed to be unique.

Use GATT attributes dbus object-paths instead of UUIDs in application's Read / Write callbacks

---

bluez/profile/device/device.go

I'm not sure, how this would've ever worked since the UUID is not part of a characteristic's path.
Signed-off-by: Sven Schwermer <sven@svenschwermer.de>

Fix (*Device1).GetDescriptors

---

api/service/app.go

This PR adds support for changing the default namespace (`app. AppInterface`) dynamically via the `app.Options`.

add AppInterface to AppOptions

---

examples/service/client.go

The error handling's `if` statement checks the wrong error and will never trigger. This PR fixes that. Caught that when my client program would never return in #103.

Fix error handling for NewDevice1

---

api/service/app.go

Previously I would get the following error while creating a service:
Connection ":1.8260" is not allowed to own the service "go.bluetooth" due to security policies in the configuration file
This PR fixes that by not requesting the go.bluetooth name. I can now create a service, while running as a normal user and without changing any system settings (on a laptop running Debian buster, with bluez 5.50).
---
I'm not sure whether this is the right fix, maybe registering the name serves a purpose. I couldn't find one so I simply deleted it in this PR.

Do not request go.bluetooth name

---

examples/discovery/discovery.go

This is **not** to be merged. I'm only opening this as a point of reference, because it seems that examples/discovery.go has some issues uncovers one that might be a root cause of a deadlock.
I didn't want to make too many changes to confuse the issue, but I think this one change might be unmasking the issues that I'm hitting.
My change will force the two defers in the discovery.Run function to be called. As this is an example, I assume that this cleanup should be done. The first defer is the cancel() for the the api.Discover(), which itself is the dbus RemoveSignal in dbus/default_handler.go, which will block waiting for a Lock.
A possibly related issue: As it is, discovery.go will block in 
`	isBeacon := <-beaconUpdated` [here](https://github.com/muka/go-bluetooth/blob/c69565a982b8f5954b …

actually make the defers get called

---

bluez/props.go
tests/watch_properties_routines_num.go

Hello
This change seems to fix the issue described in the ticket and also a potential panic caused by channel being closed while new values could still come in which caused a panic.
Attached also a script which displays the number of current go routines and demonstrates that after the fix they don't change over time, no matter how many times we subscribe to notifications.

Proposal for #113 fix

---

bluez/profile/adapter/adapter_discovery.go
bluez/props.go

This merge request recovers from a panic caused by writing to a non existing channel when scan results come in after scanning was stopped. This happens very very often in very BLE polluted areas on CPU constrained devices.
The cause was the following:
1. Scanning is stated
2. Results come in...
3. Scanning is stopped
4. More results come in
5. Until they stop coming
The crash occurred between steps 3. and 4. Now it's possible to recover from it so the whole application doesn't crash.
Suspected reason for this is that the results are still coming from a Bluez or HCI dongle RX buffer.

Deferred panic capture on OnDeviceDiscovered if scan reports come in after discovery is stopped

---

hw/linux/hciconfig/hciconfig.go

Refer to issue https://github.com/muka/go-bluetooth/issues/134
```go
hciconfig.GetAdatpers()
```
is raising a panic execption in case no BT device is connected. Similar to the corresponding `btmgmt.GetAdapers()` function it will raise an defined error, which can be handeled afterwards.
hciconfig_test.go log:
```
--- FAIL: TestGetAdapters (0.00s)
/home/thierolm/evcc/git/go-bluetooth/hw/linux/hciconfig/hciconfig_test.go:43: hciconfig provided no response
```

handle empty hciconfig response to avoid panic

---

bluez/profile/advertising/gen_LEAdvertisement1.go
bluez/profile/device/gen_Device1.go
bluez/profile/media/gen_MediaPlayer1.go
gen/generator/generator_tpl_api.go
gen/generator/generator_types.go

Properties were generated with the correct overridden type, but the raw type was being computed prior to storing the overridden  value. This fixes the method generation by ensuring the overridden type is stored prior to raw type compute.

Overridden types not propagated

---

util/map_struct.go

This PR returns nil rather than an error when a field isn't found. This change prevents the library from breaking every time BlueZ decides to add a new field to their API.
Fixes #169

Ignore fields that are not found in MapToStruct

---

util/map_struct.go

Just a simple spelling error I noticed poking around.

Fix spelling in debug message
